- name: Demo on vars on play level
  hosts: localhost
  vars:
    URL : play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

 - name: Demo on vars on task level
   hosts: localhost
   tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL : play.example.com